"""Initial schema

Revision ID: e32966e92e10
Revises: 1e5f79a587b4
Create Date: 2026-06-09 23:24:30.532281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32966e92e10'
down_revision: Union[str, Sequence[str], None] = '1e5f79a587b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_logs', sa.Column('prompt_tokens', sa.Integer(), nullable=False))
    op.add_column('query_logs', sa.Column('completion_tokens', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_logs', 'completion_tokens')
    op.drop_column('query_logs', 'prompt_tokens')
    # ### end Alembic commands ###
